=== xingchenli095/BMS/application/Application_Can/scripts/Scriptor.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <xsd:group name="Script">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element name="Decription" type="xsd:string"/>
            <xsd:element name="Expression" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Operations">
                <xsd:complexType>
                    <xsd:choice maxOccurs="unbounded" minOccurs="0">
                        <xsd:element name="Operation" type="Operation"/>
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:group>
    
    <xsd:complexType abstract="false" mixed="false" name="Script">
        <xsd:sequence>
            <xsd:group ref="Script"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:element name="Script" type="Script"></xsd:element>
    
    <xsd:group name="Operation">
        <xsd:sequence>
            <xsd:element name="Expression" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Operations">
                <xsd:complexType>
                    <xsd:choice maxOccurs="unbounded" minOccurs="0">
                        <xsd:element name="Operation" type="Operation"/>
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:group>
    
    <xsd:complexType abstract="false" mixed="false" name="Operation">
        <xsd:sequence>
            <xsd:group ref="Operation"/>
        </xsd:sequence>
        <xsd:attributeGroup ref="OperationAttributes"/>
    </xsd:complexType>
    
    <xsd:element name="Operation" type="Operation"></xsd:element>
    
    <xsd:attributeGroup name="OperationAttributes">
        <xsd:attribute name="Type" type="OperationTypeEnum">
            
        </xsd:attribute>
    </xsd:attributeGroup>
    

    
    <xsd:simpleType name="OperationTypeEnum">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ForEach"/>
            <xsd:enumeration value="SetValue"/>
            <xsd:enumeration value="Condition"/>
            <xsd:enumeration value="SetEnabled"/>
            <xsd:enumeration value="Remove"/>
            <xsd:enumeration value="Add"/>
            <xsd:enumeration value="GenerateModule"/>
            
            <xsd:enumeration value="foreach"/>
            <xsd:enumeration value="setvalue"/>
            <xsd:enumeration value="condition"/>
            <xsd:enumeration value="setenabled"/>
            <xsd:enumeration value="remove"/>
            <xsd:enumeration value="add"/>
            <xsd:enumeration value="generatemodule"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    
</xsd:schema>

=== xingchenli095/BMS/application/Application_Can/scripts/Diag_Dcm_PostImport.xml
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Scriptor.xsd">
	<Name>Diag_Dcm_PostImport</Name>
	<Decription>desc</Decription>
	<Expression>as:modconf('Dcm')[1]</Expression>
	<Operations>

		<!--		Remove Buffer added by importer-->
		<Operation Type="ForEach">
			<Expression>as:modconf('Dcm')[1]/DcmConfigSet/*[1]/DcmDsl/DcmDslBuffer/DcmBuffer_0</Expression>
			<Operations>
				<Operation Type="Remove">
					<Expression>boolean(0)</Expression>
				</Operation>
			</Operations>
		</Operation>
		
		<Operation Type= "ForEach">
			<Expression>as:modconf('Dcm')[1]/DcmConfigSet/*[1]/DcmDsl/DcmDslProtocol/DcmDslProtocolRow/DcmServiceTable_OBD/DcmDslProtocolID</Expression>
			<Operations>
				<Operation Type="SetValue">
					<Expression>'DCM_OBD_ON_CAN'</Expression>
				</Operation>
			</Operations>
		</Operation>
		
	</Operations>
</Script>

=== xingchenli095/BMS/application_can_0904/Application_Can/scripts/Split_Crc_PostImport.xml
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='Scriptor.xsd'>
	<Name>Split_Crc_PostImport</Name>
	<Decription>desc</Decription>
	<Expression>as:modconf('Crc')[1]</Expression>
	<Operations>
		<!-- Enable Crc calculation -->
		<Operation Type= "ForEach">
			<Expression>as:modconf('Crc')[1]/CrcGeneral/Crc16Mode</Expression>
			<Operations>
				<Operation Type="SetEnabled">
					<Expression>boolean(1)</Expression>
				</Operation>
			</Operations>
		</Operation>
		<Operation Type= "ForEach">
			<Expression>as:modconf('Crc')[1]/CrcGeneral/Crc32Mode</Expression>
			<Operations>
				<Operation Type="SetEnabled">
					<Expression>boolean(1)</Expression>
				</Operation>
			</Operations>
		</Operation>
		
	</Operations>
    
</Script>

=== xingchenli095/BMS/application_can_0905/Application_Can/scripts/Essential_Rte_PostImport.xml
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='Scriptor.xsd'>
    <Name>Essential_Rte_PostImport</Name>
    <Decription>desc</Decription>
    <Expression>as:modconf('Rte')[1]</Expression>
    <Operations>
    
        <!-- set rte counter -->
        <Operation Type= "Condition">
            <Expression>not(text:match(node:value(as:modconf('Rte')[1]/RteGeneration/OsCounterRef), 'ASPath:/Os/Os/HwCounter'))</Expression>
            <Operations>
                <Operation Type= "ForEach">
                    <Expression>as:modconf('Rte')[1]/RteGeneration/OsCounterRef</Expression>
                    <Operations>
                        <Operation Type="SetValue">
                            <Expression>'ASPath:/Os/Os/HwCounter'</Expression>
                        </Operation>
                    </Operations>
                </Operation>
            </Operations>
        </Operation>

    </Operations>
    
</Script>

=== xingchenli095/BMS/application/Application_Can/scripts/Essential_Dem_PostImport.xml
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='Scriptor.xsd'>
	<Name>Essential_Dem_PostImport</Name>
	<Decription>desc</Decription>
	<Expression>as:modconf('Dem')[1]</Expression>
	<Operations>
	
		<Operation Type= "Condition">
            <Expression>node:exists(as:modconf('Dem')[1]/DemConfigSet/*[1]/DemEventParameter/Permanent_DTC/DemEventClass/DemDebounceAlgorithmClass/DemCallbackGetFDC)</Expression>
            <Operations>
                <Operation Type= "ForEach">
                    <Expression>as:modconf('Dem')[1]/DemConfigSet/*[1]/DemEventParameter/Permanent_DTC/DemEventClass/DemDebounceAlgorithmClass/DemCallbackGetFDC</Expression>
                    <Operations>
                        <Operation Type="SetEnabled">
                            <Expression>boolean(0)</Expression>
                        </Operation>
                    </Operations>
                </Operation>
            </Operations>
		</Operation>
		
	</Operations>
</Script>

=== xingchenli095/BMS/application_can_0904/Application_Can/scripts/Split_CAN_RAM_Blocks_Post.xml
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Scriptor.xsd">
	<Name>Split_CAN_RAM_Blocks_Post</Name>
	<Decription>desc</Decription>
	<Expression>as:modconf('Can')[1]</Expression>
	<Operations>

		<!--		enable CanHwObjectUsesBlock and set it to CAN as default     -->
		<Operation Type="ForEach">
			<Expression>as:modconf('Can')[1]/CanConfigSet/CanHardwareObject/*</Expression>
			<Operations>	
			    <Operation Type="ForEach">
				    <Expression>./CanHwObjectUsesBlock</Expression>
					<Operations>
						<Operation Type="SetEnabled">
							<Expression>boolean(1)</Expression>
						</Operation>
					</Operations>
				</Operation>
				<Operation Type="ForEach">
				    <Expression>./CanHwObjectUsesBlock</Expression>
					<Operations>
						<Operation Type="SetValue">
							<Expression>'CAN_RAM_BLOCK_0'</Expression>
						</Operation>
					</Operations>
				</Operation>
			</Operations>
		</Operation>
		
		<!--		search for CANFD references in CanIfRxPduCfg  -->
		<Operation Type="ForEach">
			<Expression>as:modconf('CanIf')[1]/CanIfInitCfg/*[1]/CanIfRxPduCfg/*</Expression>
			<Operations>
				<Operation Type="Condition">
					<Expression>(./CanIfRxPduCanIdType = 'STANDARD_FD_CAN') or (./CanIfRxPduCanIdType = 'EXTENDED_FD_CAN')</Expression>
					<Operations>
						<Operation Type="ForEach">
							<Expression>node:ref(node:ref(./CanIfRxPduHrhIdRef/*[1])/CanIfHrhIdSymRef)/CanHwObjectUsesBlock</Expression>
							<Operations>
								<Operation Type="SetValue">
									<Expression>'CAN_RAM_BLOCK_1'</Expression>
								</Operation>
							</Operations>
						</Operation>
					</Operations>
				</Operation>
			</Operations>
		</Operation>
			
		<!--		search for CANFD references in CanIfTxPduCfg  -->
		<Operation Type="ForEach">
			<Expression>as:modconf('CanIf')[1]/CanIfInitCfg/*[1]/CanIfTxPduCfg/*</Expression>
			<Operations>
				<Operation Type="Condition">
					<Expression>(./CanIfTxPduCanIdType = 'STANDARD_FD_CAN') or (./CanIfTxPduCanIdType = 'EXTENDED_FD_CAN')</Expression>
					<Operations>
						<Operation Type="ForEach">
							<Expression>node:ref(node:ref(node:ref(./CanIfTxPduBufferRef)/CanIfBufferHthRef/*[1])/CanIfHthIdSymRef)/CanHwObjectUsesBlock</Expression>
							<Operations>
								<Operation Type="SetValue">
									<Expression>'CAN_RAM_BLOCK_1'</Expression>
								</Operation>
							</Operations>
						</Operation>
					</Operations>
				</Operation>
			</Operations>
		</Operation>
		
		
	</Operations>
</Script>

=== xingchenli095/BMS/application_can_0904/Application_Can/scripts/Split_Port_PostImport.xml
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='Scriptor.xsd'>
	<Name>Split_Port_PostImport</Name>
	<Decription>desc</Decription>
	<Expression>as:modconf('Port')[1]</Expression>
	<Operations>

		<Operation Type= "ForEach">
			<Expression>as:modconf('Port')[1]/PortConfigSet/PortContainer/*/PortPin/*/PortPinMode</Expression>
			<Operations>
				<Operation Type= "Condition">
				<Expression>not(node:exists(./*))</Expression>
					<Operations>
						<Operation Type="Add">
							<Expression>'PORT_PIN_MODE_ALL'</Expression>
						</Operation>
					</Operations>
				</Operation>
			</Operations>	
		</Operation>

	</Operations>
</Script>
